<?php


namespace Imanghafoori\LaravelMicroscope\Tests;


use Imanghafoori\LaravelMicroscope\Analyzers\ComposerJson;
use Orchestra\Testbench\TestCase;

class ComposerJsonClassTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        dd(public_path());
        copy(get_include_path('/stubs/composer.json'),'vendor/orchestra/testbench-core/laravel');
    }



    public function test(){
        dump('-');
        $d = app()->basePath();
        dump(system('ls '.$d));
        dump('+');
        $this->assertFalse(false);

    }

}
